# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bored' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bored
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'SwiftyJSON', '~> 4.0'

  target 'BoredTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoredUITests' do
    # Pods for testing
  end

end
